### ISSUE TITLE
Migrate wiki content

### ISSUE THREAD

**Issue by christianbauer** [openremote/Documentation#2]
- [ ] Find out if Github Wiki has everything we need

**Comment by bensteUEM** [comment]
So far it looks nicely cleaned but e.g. i'm missing the Synology specific pages in particular in regards to the package installation and zwave

**Comment by pierrekil** [comment]
Controller pages still missing, especially Windows, Mac, Raspberry, Synology. For now only available in 'Get Started' overview: http://www.openremote.com/install-the-controller/
